export const MODULE_ICONS: Record<string, string> = {
  contracts: '📝',
  subsystems: '🔧',
  tasks: '📋',
  brigades: '👷',
  completion: '📦',
  prefabrication: '🏭',
  network: '🌐',
  warehouse: '🏪',
  bom: '🔩',
  devices: '📱',
  reports: '📈',
  documents: '📄',
  photos: '📷',
  users: '👥',
  notifications: '🔔',
  realization: '🛠️',
  settings: '⚙️',
  admin: '🛡️',
  dashboard: '📊',
  logout: '🚪',
  mapa: '🗺️',
  cars: '🚗',
  assets: '🏗️',
};
