// src/components/contracts/wizard/utils/taskDataNormalizer.ts
// Normalizes wizard TaskDetail to a consistent shape used across both wizards
// (ContractWizardModal and ExtendWizardModal) for the topology diagram.

import type { TaskDetail } from '../types/wizard.types';
import { parseWizardKilometraz } from './fiberTaskUtils';
import { formatKilometrazDisplay } from './validation';
import { generateTaskName } from './taskNameGenerator';

/**
 * Canonical task representation consumed by NetworkTopologyStep.
 * Both the sidebar list and the canvas nodes are built from this shape so
 * that labels and identifiers are always computed by the same logic.
 */
export interface NormalizedTaskData {
  /** Stable identifier: taskWizardId > task.id.toString() > positional fallback */
  id: string;
  /** Display label generated by generateTaskName (same as the read-only `nazwa` field) */
  label: string;
  /** Kilometraż formatted as "XXX,XXX", undefined when not set */
  kilometraz?: string;
  /** Kilometraż parsed to a numeric km value for distance calculations */
  kilometrazNumeric?: number;
  /** Original task type */
  type: TaskDetail['taskType'];
  /** True when the task already exists in the database (has an `id`) */
  isExisting: boolean;
}

/**
 * Derive a stable, display-ready representation from a wizard `TaskDetail`.
 *
 * @param task          - The raw TaskDetail from wizardData.subsystems[n].taskDetails
 * @param index         - Positional index within the taskDetails array (used as last-resort ID)
 * @param liniaKolejowa - Optional railway line inherited from the subsystem/contract level
 */
export const normalizeTaskData = (
  task: TaskDetail,
  index: number,
  liniaKolejowa?: string
): NormalizedTaskData => {
  // 1. Stable identifier: prefer wizard UUID → DB numeric id → positional fallback
  const id =
    task.taskWizardId ??
    (task.id !== undefined ? String(task.id) : `task-${index}`);

  // 2. Kilometraż formatting
  const kilometrazNumeric = parseWizardKilometraz(task.kilometraz);
  const kilometraz = task.kilometraz ? formatKilometrazDisplay(task.kilometraz) : undefined;

  // 3. Label — reuse the same generateTaskName logic the detail steps use,
  //    so the topology diagram always shows the same text as the wizard form.
  const lk = task.liniaKolejowa || liniaKolejowa;
  const taskWithFormattedKm: TaskDetail = kilometraz
    ? { ...task, kilometraz, liniaKolejowa: lk }
    : { ...task, liniaKolejowa: lk };

  const label =
    generateTaskName(task.taskType, taskWithFormattedKm, lk) ||
    task.nazwa ||
    task.taskType ||
    `Zadanie ${index + 1}`;

  return {
    id,
    label,
    kilometraz,
    kilometrazNumeric,
    type: task.taskType,
    isExisting: task.id !== undefined,
  };
};
